[versions]
agp = "8.13.1"
cameraCore = "1.5.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
exifinterface = "1.3.6"

[libraries]
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCore" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCore" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

