plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.demonoframework'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "com.example.demonoframework"
        minSdk 29
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation libs.camera.core
    implementation libs.camera.camera2
    implementation libs.camera.lifecycle
    implementation libs.camera.view

    //api libs.boofcv.android
    implementation libs.boofcv.android
    implementation libs.boofcv.core
    implementation libs.boofcv.geo
    implementation libs.boofcv.io
    implementation libs.boofcv.sfm

    implementation libs.media3.exoplayer
    implementation libs.androidx.media3.ui
    implementation libs.androidx.media3.common
    implementation libs.androidx.media3.inspector

    implementation project(':opencv')
}